name: Bug Report
description: File a bug report on the Terraform Modules
labels: ["Type: Bug", "Status: Triage"]
body:
  - type: markdown
    attributes:
      value: >
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: >
        If applicable, add screenshots to help explain the problem you are facing.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: To Reproduce
      description: >
        Please provide a step-by-step instruction of how to reproduce the behavior.
      placeholder: |
        1. `terraform plan ...`
        2. `terraform apply ...`
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: >
        - Terraform version
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: >
        Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context

