name: Test

on:
  push:
    branches:
      - main

jobs:
  fmt-test:
    name: Check Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ secrets.TERRAFORM_VERSION }}

      - name: Run terraform fmt
        id: fmt
        run: terraform fmt -check -recursive ./modules

  required_status_checks:
    name: Required Terraform Test Status Checks
    runs-on: ubuntu-latest
    needs:
      - fmt-test
    if: always() && !cancelled()
    timeout-minutes: 5
    steps:
      - run: |
          [ '${{ needs.fmt-validate-test.result }}' = 'success' ] || (echo fmt-validate-test failed && false)
